// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpOmFVd6pEZXpeMKa92-mqzmVL6d5ba8o',
    appId: '1:92341196379:web:28f832350e5758e1b5517e',
    messagingSenderId: '92341196379',
    projectId: 'chat-app-bf884',
    authDomain: 'chat-app-bf884.firebaseapp.com',
    storageBucket: 'chat-app-bf884.appspot.com',
    measurementId: 'G-1JE4ERFWC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_i8D5BNubp5nZAZPGwfFLN-bFZL8VZI',
    appId: '1:92341196379:android:c1eff4291af79093b5517e',
    messagingSenderId: '92341196379',
    projectId: 'chat-app-bf884',
    storageBucket: 'chat-app-bf884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8UzGj4QegYjNAUL9f_tb4G866yrZhm4',
    appId: '1:92341196379:ios:d46b43c311eb2611b5517e',
    messagingSenderId: '92341196379',
    projectId: 'chat-app-bf884',
    storageBucket: 'chat-app-bf884.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe8UzGj4QegYjNAUL9f_tb4G866yrZhm4',
    appId: '1:92341196379:ios:d46b43c311eb2611b5517e',
    messagingSenderId: '92341196379',
    projectId: 'chat-app-bf884',
    storageBucket: 'chat-app-bf884.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpOmFVd6pEZXpeMKa92-mqzmVL6d5ba8o',
    appId: '1:92341196379:web:aa87f255ac4b7747b5517e',
    messagingSenderId: '92341196379',
    projectId: 'chat-app-bf884',
    authDomain: 'chat-app-bf884.firebaseapp.com',
    storageBucket: 'chat-app-bf884.appspot.com',
    measurementId: 'G-S8D0SH881C',
  );
}
